apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: my-node-app
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: node-app
    spec:
      containers:
      - name: nginx
        # Run this image
        image: arpitkvictus2004/webapp-demo:02
        

# ---
# service-node-app.yml 


# kind: Service
# apiVersion: v1
# metadata:
#   # Unique key of the Service instance
#   name: service-my-node-app
# spec:
#   ports:
#     # Accept traffic sent to port 80
#     - name: http
#       port: 8080
#       targetPort: 3000
#   selector:
#     # Loadbalance traffic across Pods matching
#     # this label selector
#     app: node-app
#   # Create an HA proxy in the cloud provider
#   # with an External IP address - *Only supported
#   # by some cloud providers*
#   type: LoadBalancer
